name: Brad Weinberger
bio: 'software engineer'
picture: 'assets/images/profile.jpg'

url: http://bradweinberger.com
permalink: /:title/

analytics: 'UA-73430609-1'
linkedin: brad-weinberger-bb5a3554
github: BradleyMarie
email: me@bradweinberger.com
